# Generated by Django 5.1.3 on 2024-12-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_question_quiz_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.question'),
            preserve_default=False,
        ),
    ]
