# Generated by Django 5.1.3 on 2024-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_answer_answer_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (leave blank for no time limit)', null=True),
        ),
    ]
