# Generated by Django 5.1.3 on 2024-12-20 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quiz_time_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='played_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
